### ISSUE TITLE
Can't install Your plugins

### ISSUE THREAD

**Issue by Pocokk** [TuckerWarlock/qbittorrent-search-plugins#1]
Hey there,

Qbittorrent 4.6.2 64-bit version

I can't install Your btdig or bt4gprx plugins, it says plugin is not supported.

Could you have a look please? Thank you.

**Comment by TuckerWarlock** [comment]
@Pocokk apologies, the plugin does not work for qBit 4.6.x. This was only tested working for 4.5.x
See this page for supported versions: https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins

Additionally the btdig.com plugin is a work in progress (WIP) and I have not fleshed it out yet.

**Comment by TuckerWarlock** [comment]
@Pocokk tested this out further and was able to confirm the bt4gprx plugin works with the current version of qBittorrent v4.6.3 and the current version of Python 3.12.1.

![image](https://github.com/TuckerWarlock/qbittorrent-search-plugins/assets/59034283/607cbf88-7c9e-463b-a2ed-df40a096db6f)

I was able to find a couple of open issues from users with similar problems and the fix was re-installing Python
https://github.com/qbittorrent/qBittorrent/issues/19332#issuecomment-1656787762
https://github.com/qbittorrent/qBittorrent/issues/20104#issuecomment-1876923779

Just checking the qBittorrent issues page there are 80+ open issues related to the SearchEngine, so your issue could also be related to an underlying issue with the software itself
https://github.com/qbittorrent/qBittorrent/labels/Search%20engine

**Comment by Pocokk** [comment]
It is a relatively fresh Python install (1-2 months olds) with default/vanilla settings, nothing changed or added or modified (I installed and left it there, didn't touch anything), so I don't think that's the issue here. 

Thank you for your answer, hopefully the devs will fix it on their end!

**Comment by TuckerWarlock** [comment]
@Pocokk it seems to be a mixture of Python, upgrading qBittorrent, and the search engine plugins themselves. It's too bad it's been a continuous issue for multiple users over the past few years https://github.com/qbittorrent/qBittorrent/issues/13122

While troubleshooting I found that my 4.5.x install persisted files during the 4.6.x upgrade, one of the engines in the source code was still present even though it had been removed https://github.com/qbittorrent/qBittorrent/commit/62d96c068ae46d6354695b2469a922e09f697cd1

Might be worth trying to remove the existing engines folder and having qBit regenerate them (this requires reinstalling all plugins supported/unsupported) https://github.com/qbittorrent/qBittorrent/issues/11149#issuecomment-531564986

**Comment by Pocokk** [comment]
One last thing to add, is that I've noticed this "issue" (so to speak) doesn't correlate to every plugin search script, but rather only for a select few.
